name: Check Branches

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - main
      - backup

jobs:
  check-branches:
    runs-on: ubuntu-latest

    permissions:
      issues: read
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Ensure script is executable
        run: chmod +x check_branches.py

      - name: Run branch check script
        run: python check_branches.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}