name: Check Branches

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - main
      - backup

jobs:
  check-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: List issues in README
        uses: actions/github-script@v4
        with:
          script: |
            const { issues } = await github.paginate(github.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all'
            });

            const issueTable = issues.map(issue => `| ${issue.number} | ${issue.title} | ${issue.state} |`).join('\n');

            const readmePath = './README.md';
            const fs = require('fs');
            let readmeContent = fs.readFileSync(readmePath, 'utf8');

            const startMarker = '<!-- issueTable -->';
            const endMarker = '<!-- /issueTable -->';
            const startIndex = readmeContent.indexOf(startMarker) + startMarker.length;
            const endIndex = readmeContent.indexOf(endMarker);

            if (startIndex === -1 || endIndex === -1) {
              core.setFailed('Markers not found in README.md');
              return;
            }

            const newContent = `${startMarker}\n| Number | Title | State |\n|--------|-------|-------|\n${issueTable}\n${endMarker}`;
            readmeContent = readmeContent.slice(0, startIndex) + newContent + readmeContent.slice(endIndex);

            fs.writeFileSync(readmePath, readmeContent);

            await github.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'README.md',
              message: 'Update issue list in README',
              content: Buffer.from(readmeContent).toString('base64'),
              sha: (await github.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README.md'
              })).data.sha
            });