name: Deploy to Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy changes
        run: |
          echo "Deploying changes to master branch."
          # Add your deployment scripts or commands here